/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import javax.swing.JOptionPane;

/**
 *
 * @author alonso
 */
public class SolicitarCita extends javax.swing.JFrame {
    ClienteCitasMedicasTCP cliente = new ClienteCitasMedicasTCP(); 
    /**
     * Creates new form SolicitarCita
     */
    public SolicitarCita() {
        this.setTitle("Asistente para Solicitar cita previa"); 
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorFormatoDNI = new javax.swing.JDialog();
        cajaDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cajaDia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaAnio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menuEspecialidades = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        botonMandarSolicitud = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        menuMeses = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        errorFormatoDNI.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                errorFormatoDNIComponentShown(evt);
            }
        });

        javax.swing.GroupLayout errorFormatoDNILayout = new javax.swing.GroupLayout(errorFormatoDNI.getContentPane());
        errorFormatoDNI.getContentPane().setLayout(errorFormatoDNILayout);
        errorFormatoDNILayout.setHorizontalGroup(
            errorFormatoDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        errorFormatoDNILayout.setVerticalGroup(
            errorFormatoDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cajaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDNIActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduzca su DNI:");

        cajaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDiaActionPerformed(evt);
            }
        });

        jLabel2.setText("Introduzca el día:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel3.setText("Este asistente le ayudará a solicitar una cita rápidamente. ");

        jLabel4.setText("Seleccione el mes:");

        jLabel5.setText("Introduzca el año:");

        menuEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRAUMATOLOGIA", "CARDIOLOGIA", "MEDICINA GENERAL", "NEUROLOGIA" }));
        menuEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspecialidadesActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione especialidad:");

        botonMandarSolicitud.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botonMandarSolicitud.setText("SOLICITAR CITA");
        botonMandarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMandarSolicitudActionPerformed(evt);
            }
        });

        jLabel7.setText("Rellene los siguiente campos, después seleccione \"SOLICITAR CITA\"");

        menuMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("1. Datos del paciente:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("2. Datos sobre la cita a solicitar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaDia)
                                    .addComponent(cajaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuEspecialidades, 0, 1, Short.MAX_VALUE)
                            .addComponent(cajaAnio)
                            .addComponent(menuMeses, 0, 130, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMandarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(menuMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMandarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDNIActionPerformed

    // mandar solicitud cliente
    private void botonMandarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMandarSolicitudActionPerformed
        // hacer comprobaciones sobre los valores introducidos
        boolean todo_ok = comprobarCamposIntroducidos();
        
        if (todo_ok){ // formar la cadena de String para mandarla al servidor
            String cad = new String();
            cad += cajaDia.getText()  + "/" + (menuMeses.getSelectedIndex()+1) + "/" + cajaAnio.getText()+ "#";
    //buferEnvio = buferEnvio + cadDia + "/" + cadMes + "/" + cadAnio + "#";

            cad += menuEspecialidades.getSelectedItem() + "#" ; 

            cad += cajaDNI.getText() + "#" ;

            cad += "1" + "#" ; 

            System.out.println("-------> "+ cad);

            System.out.println("Soy el cliente " + cliente.getId() + " y ya me han llamado !!");
            cliente.procesar(cad);
            
            System.out.println("Transacción final...");
            
            String fechaDada = cliente.getBuferRecepcion(); 
            JOptionPane.showMessageDialog(this, "Tu cita es a las: "+ fechaDada , "Notificación de cita asignada", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonMandarSolicitudActionPerformed

    private void errorFormatoDNIComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_errorFormatoDNIComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_errorFormatoDNIComponentShown

    private void menuEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEspecialidadesActionPerformed

    private void cajaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDiaActionPerformed

    
    private boolean comprobarCamposIntroducidos ()
    {
        boolean errorDNI =false, 
                errorDia=false, 
                errorMes=false, 
                errorAnio=false;
        
        // comprobar el formato del DNI
        // ¡OJO! Aquí se comprueba el formato, no si el DNI existe o no.
        if (cajaDNI.getText().length() != 9)
        {
            errorDNI = true;
        }
        
        if (cajaDia.getText().length() != 0){
            if ( Integer.parseInt(cajaDia.getText()) <= 1 && Integer.parseInt(cajaDia.getText()) <= 31  )
                errorDia = true; 
        }
        else errorDia = true; 

        int mes = menuMeses.getSelectedIndex()+1;
        System.out.println(mes);
        
        if (mes < 1 || mes > 12)
            errorMes = true; 
        
        if (cajaAnio.getText().length() != 0)
        {
            if ( Integer.parseInt(cajaAnio.getText()) < 2000 || 
                 Integer.parseInt(cajaAnio.getText()) > 2999  )
            {
                errorAnio = true;
                System.out.println("FECHA en rango INcorrecto !!!!!");
            }
        }
        else errorAnio = true; 
        
        System.out.println(errorDNI + "  "+ errorDia + " " + errorMes + "  " + errorAnio); 
        
        // MOSTRAR CUADRO DE DIALOGO
        if (errorDNI || errorDia || errorMes || errorAnio) 
        {
            JOptionPane.showMessageDialog(this, "Algo has introducido mal...", "Alerta sobre datos incorrectos", JOptionPane.ERROR_MESSAGE);
        }
        
        if ( !errorDNI && !errorDia && !errorMes && !errorAnio )
            return true;
        else return false; 
    
    } // fin método comprobaciones
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMandarSolicitud;
    private javax.swing.JTextField cajaAnio;
    private javax.swing.JTextField cajaDNI;
    private javax.swing.JTextField cajaDia;
    private javax.swing.JDialog errorFormatoDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> menuEspecialidades;
    private javax.swing.JComboBox<String> menuMeses;
    // End of variables declaration//GEN-END:variables
}
